apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch-hq.fullname" . }}
  labels:
    {{- include "elasticsearch-hq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if hasKey .Values.service "nodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "elasticsearch-hq.selectorLabels" . | nindent 4 }}
