{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  mariadb-root-password: {{ print .Values.auth.rootPassword | b64enc | quote }}
  {{- if .Values.auth.username }}
  mariadb-password: {{ print .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
