# default service account token no longer created by kubernetes,
# but still needed by PasslessOperator
{{- if semverCompare ">=1.22-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passless-operator.fullname" . }}-masterkey
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "default"
type: kubernetes.io/service-account-token
data: {}
{{- end }}
