apiVersion: v1
kind: Service
metadata:
  name: {{ include "kivitendo.fullname" . }}
  labels:
    {{- include "kivitendo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "kivitendo.selectorLabels" . | nindent 4 }}
